inherit_from: .hound_defaults.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/initializers/devise.rb'

# Ruby Style
Metrics/LineLength:
  Max: 100
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: when_needed
  SupportedStyles:
    # `when_needed` will add the frozen string literal comment to files
    # only when the `TargetRubyVersion` is set to 2.3+.
    - when_needed
      # `always` will always add the frozen string literal comment to a file
      # regardless of the Ruby version or if `freeze` or `<<` are called on a
      # string literal. If you run code against multiple versions of Ruby, it is
      # possible that this will create errors in Ruby 2.3.0+.
    - always
Style/MultilineOperationIndentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - no_comma

# Rails Styles
Rails/HasAndBelongsToMany:
  Enabled: false

# RSpec Styles
RSpec/DescribedClass:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 20
RSpec/FilePath:
  Enabled: false
