inherit_from: .hound_defaults.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/initializers/devise.rb'
    - 'app/helpers/devise_helper.rb'
    - 'Guardfile'

# Ruby Style
Metrics/LineLength:
  Max: 100
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: when_needed
  SupportedStyles:
    # `when_needed` will add the frozen string literal comment to files
    # only when the `TargetRubyVersion` is set to 2.3+.
    - when_needed
      # `always` will always add the frozen string literal comment to a file
      # regardless of the Ruby version or if `freeze` or `<<` are called on a
      # string literal. If you run code against multiple versions of Ruby, it is
      # possible that this will create errors in Ruby 2.3.0+.
    - always
Style/MultilineOperationIndentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - no_comma

# Rails Styles
Rails/HasAndBelongsToMany:
  Enabled: false

# RSpec Styles
RSpec/AnyInstance:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true
  Max: 30
RSpec/MultipleExpectations:
  Description: Checks if examples contain too many `expect` calls.
  Enabled: true
  Max: 6
RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: true
  MaxNesting: 3
RSpec/VerifiedDoubles:
  # Note, we are already doing this by default. See spec/spec_helper.rb
  Description: Prefer using verifying doubles over normal doubles.
  Enabled: false
  IgnoreSymbolicNames: false
