# https://github.com/mperham/sidekiq/wiki/Advanced-Options#the-sidekiq-configuration-file
:concurrency: 1
staging:
  :concurrency: 10
production:
  :concurrency: <%= ENV['WORKER_CONCURRENCY'] | 15 %>
:queues:
  - 'default'
  - ['elasticsearch', 2]
